package ClientManager;

public enum ActionType {
	STOP_TRACK,
	START_TRACK,
	TRANSFER_TRACK,
	SKIP_TRACK,
	PAUSE_TRACK,
	SETTINGS_UPDATE,
	REMOVE_TRACK,
	STOP_DEVICE,
	SWAP_TRACK_POSITION,
	SET_PLAYBACK_POSITION
}
